spring:
  application:
    name: service-user
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: munna
    password: munna1234
    url: jdbc:oracle:thin:@localhost:1521:orcl

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 8081

eureka:
  instance:
    hostname: localhost