spring:
  application:
    name: item-service

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: munna
    password: munna1234
    url: jdbc:oracle:thin:@localhost:1521:orcl

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  instance:
    hostname: localhost